WIDTH = 10
HEIGHT = 20
SCALE = 30
FPS = 60
ELEMENT_SIZE = 28
ELEMENT_RADIUS = 3
SCORE_COLOR = "white"
INITIAL_SPEED_DELAY = FPS/2
SNAKE_COLOR = "YELLOW"
APPLE_COLOR = "red"
GAME_OVER_COLOR = "red"

SCREEN_COLOR = "black"